version: "3.7"

services:
  react-proj:
    # service 1 container name
    container_name: tesrt
    build:
     
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "91:3000"
   
    volumes:
      - "/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
